### PR TITLE
Modify session.data type

### PR DESCRIPTION
**Pull request by mathieug**

### CODE REVIEW

**Comment by donpark** [comment]
@mathieu, I have migration concerns. Have you checked effect of changing existing SchemaType from string to Mixed?

I guess this depends largely on what mongoose or mongodb does when it sees a string where mixed type is expected.

If there is a significant performance gain, this will be worth the migration hiccup (delete all live session).

**Comment by mathieug** [comment]
@donpark : No, could you check? I'll try on monday.

**Comment by donpark** [comment]
I found some time to try this and result is mixed.

Following exception is thrown from createSession function in `connect` if an unexpired session record stored as string is fetched as Mixed.

```
    500 TypeError: Cannot read property 'expires' of undefined
    at SessionStore.Store.createSession (/Users/don/dev/session-mongoose-test/node_modules/connect/lib/middleware/session/store.js:78:28)
    at /Users/don/dev/session-mongoose-test/node_modules/connect/lib/middleware/session.js:340:15
    at Promise.SessionStore.get (/Users/don/dev/session-mongoose-test/node_modules/session-mongoose/index.js:58:20)
    at Promise.addBack (/Users/don/dev/session-mongoose-test/node_modules/session-mongoose/node_modules/mongeese/node_modules/mongoose/lib/promise.js:128:8)
    at Promise.EventEmitter.emit (events.js:88:17)
    at Promise.emit (/Users/don/dev/session-mongoose-test/node_modules/session-mongoose/node_modules/mongeese/node_modules/mongoose/lib/promise.js:66:38)
    at Promise.complete (/Users/don/dev/session-mongoose-test/node_modules/session-mongoose/node_modules/mongeese/node_modules/mongoose/lib/promise.js:77:20)
    at Query.findOne (/Users/don/dev/session-mongoose-test/node_modules/session-mongoose/node_modules/mongeese/node_modules/mongoose/lib/query.js:1458:15)
    at model.Document.init (/Users/don/dev/session-mongoose-test/node_modules/session-mongoose/node_modules/mongeese/node_modules/mongoose/lib/document.js:212:11)
    at model.init (/Users/don/dev/session-mongoose-test/node_modules/session-mongoose/node_modules/mongeese/node_modules/mongoose/lib/model.js:193:36)
```

There might be some workarounds but, at this time, I don't think whatever gain from this change is worth the trouble it might cause.

Sorry. :-(

**Comment by mathieug** [comment]
Sorry about the CoffeeScript version

**Comment by donpark** [comment]
Does that fix the migration issue? If so then I guess it'll be alright to merge.

**Comment by donpark** [comment]
I've merged your .coffee file changes then made the same fix you made in .js file.
Unfortunately, `npm publish` is broken currently so push to npm will have to wait.

**Comment by donpark** [comment]
I did confirm that fix resolved migration issue and that session does get written out properly as Mixed on update.

**Comment by mathieug** [comment]
Yatta!
Thanks

**Comment by donpark** [comment]
published using npm 1.1.59. yeah

**Pull request merged**
