### PR TITLE
Ability to turn off the sweeper

### PR DESCRIPTION
**Pull request by luccastera**
I've found that the sweeper was misbehaving and making a lot of mongodb requests. It looks like it was stuck in an infinite loop.

I also realized that some people might not want to have the sweeper running (in my case for example).

So I've added a way to turn off the sweeper by passing a sweeper: false option. The sweeper bug is not fixed by this pull request. The option to bypass it is all i need because I want to expire my sessions separately.

The following graph shows the drop in mongodb requests in a sample application after turning off the sweeper.

screen shot 2013-06-03 at 2 13 18 pm

### CODE REVIEW

**Comment by pronebird** [comment]
Can you show your config for session-mongoose and for cookies?

**Comment by luccastera** [comment]
Before, when I had the problem with the sweeper, my config was:

{ url: dbURL, interval: 31536000000 }

After my change, my new config looks like:

{url: dbURL, sweeper: false}

**Comment by pronebird** [comment]
I experienced similar when I forgot to setup cookies maxAge. Could you please check your cookies' settings?

``` javascript
app.use(express.session({
  secret: "secret123",
  cookie: { 
    maxAge: 3.6e+6 * 10, // 10 hours
    httpOnly: false,
    path: '/'
  },
  store: new sessionMongoose({
    interval: 4.32e+6, // 1.2 hours
    connection: mongoose.connection
  })
}));
```

**Comment by donpark** [comment]
Merged cause, possible configuration aside, this change won't hurt nor complicate the code much. Thanks @dambalah

**Pull request merged**
